[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
base64 = "0.21.0"
ring = "0.17.8"
rand = "0.8.5"
chrono = "0.4.38"
sha2 = "0.10.6"
uuid = {version = "1.10.0", features = ["v4"]}
derive_more = "^0.99"

